version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/app .

  run:
    desc: Run the built app
    deps: [build]
    cmds:
      - ./bin/app

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin
